/**
 * Auto-generated Storyblok TypeScript types
 *
 * This file is automatically generated by scripts/generate-storyblok-types.ts
 * Do not edit this file manually. Run 'npm run generate:types' to regenerate.
 *
 * Generated at: 2025-12-28T10:18:18.641Z
 */

// Storyblok helper types
export interface StoryblokAsset {
  id: number;
  alt: string;
  name: string;
  focus: string;
  title: string;
  filename: string;
  copyright: string;
  fieldtype: string;
}

export interface StoryblokLink {
  id: string;
  url: string;
  linktype: string;
  fieldtype: string;
  cached_url?: string;
}

export interface StoryblokMultilink {
  id?: string;
  url?: string;
  linktype: string;
  fieldtype: string;
  cached_url?: string;
  target?: string;
  email?: string;
  story?: {
    uuid: string;
    id: number;
    name: string;
    slug: string;
    full_slug: string;
  };
}

// Base interface for all Storyblok components
export interface StoryblokComponentBase {
  _uid: string;
  _editable?: string;
  component: string;
}

export interface ArticleContentBlok {
  headline?: string;
  content?: StoryblokComponent[];
  preview_image?: StoryblokAsset;
}

export interface BlogPageBlok {
  title?: string;
  slug?: string;
  content?: {
    body?: ArticleContentBlok[];
  };
  author?: string;
  date?: string;
  image_preview?: StoryblokAsset;
}

export interface BlogPreviewBlok {
  headline?: string;
  articles?: BlogPageBlok[];
}

export interface CenteredTextBlockBlok {
  content?: (HeadlineBlok | LinkBlok | ParagraphBlok)[];
}

export interface ChefCardBlok {
  name?: string;
  stand?: string;
  link?: StoryblokMultilink;
  media?: MediaBlok;
  _uid?: string;
  country?: string;
}

export interface ChefsAndPitmastersBlok {
  content?: (HeadlineBlok | ParagraphBlok)[];
  description?: string;
  chefs?: ChefCardBlok[];
}

export interface SectionBlok {
  _uid?: string;
  content?: (CenteredTextBlockBlok | MediaBlok | StoryblokComponent)[];
  height?: string;
  padding?: string;
  backgroundColor?: string;
  anchor?: string; // Optional anchor ID for linking to this section
}

export interface GridBlok {
  content?: (CenteredTextBlockBlok | MediaBlok | StoryblokComponent)[];
  nColsLarge?: number;
  nColsMedium?: number;
  nColsMobile?: number;
  gap?: string;
}

export interface MasonryGridBlok {
  content?: (CenteredTextBlockBlok | MediaBlok | StoryblokComponent)[];
  nColsLarge?: number;
  nColsMedium?: number;
  nColsMobile?: number;
  gap?: string;
}

export interface ContainerBlok {
  content?: (CenteredTextBlockBlok | MediaBlok | StoryblokComponent)[];
  colSpanDesktop?: number;
  colSpanMobile?: number;
  rowSpanDesktop?: number;
  rowSpanMobile?: number;
  backgroundColor?: string;
  backgroundMedia?: MediaBlok;
  customHeight?: string;
  customWidth?: string;
  paddingMobile?: string;
  paddingDesktop?: string;
  paddingDesktopLarge?: string;
}
export interface EventCardBlok {
  title?: string;
  date?: string;
  subtitle?: string;
  media?: MediaBlok;
  link?: string;
}
export interface CarouselContainerBlok {
  content?: (CenteredTextBlockBlok | MediaBlok | StoryblokComponent)[];
  slideWidth?: string;
}

export interface EventBannerBlok {
  location?: string;
  date?: string;
}

export interface FeatureBlok {
  name?: string;
}

export interface GlobalConfigBlok {
  header_menu?: MenuItemBlok[];
  footer_menu?: MenuItemBlok[];
  date?: string;
  address?: string;
  phone?: string;
  email?: string;
  label_link_location?: string;
  link_location?: string;
  city?: string;
  tickets?: string;
  tickets_slug?: string;
  tickets_b2c_label?: string;
  tickets_b2c_slug?: string;
  tickets_b2b_label?: string;
  tickets_b2b_slug?: string;
}

export interface GridBlok {
  columns?: StoryblokComponent[];
}

export interface HeadlineBlok {
  content?: string;
  color?: string;
  heading?: "h1" | "h2" | "h3" | "h4" | "h5" | "hero";
  textAlign?: "start" | "center" | "end";
}

export interface HeroVideoBlok {
  headline?: string;
  media?: MediaBlok;
  media_background?: MediaBlok;
}

export interface LinkBlok {
  _uid?: string;
  label?: string;
  path?: string;
  style?:
    | "filled-dark"
    | "filled-light"
    | "outline-dark"
    | "outline-light"
    | "link";
  icon?: "arrow-right" | "arrow-external-link";
  fullWidth?: boolean;
}

export interface MediaBlok {
  filename?: string;
  alt?: string;
  name?: string;
}

export interface MenuItemBlok {
  label?: string;
  link?: string;
  external?: boolean;
  submenu?: MenuItemBlok[];
  _uid?: string;
}

export interface PageBlok {
  content?: {
    body?: StoryblokComponent[];
  };
}

export interface ParagraphBlok {
  content?: string;
  color?: string;
  textAlign?: "start" | "center" | "end";
  bold?: boolean;
}

export interface PartnerBlok {
  name?: string;
  logo?: StoryblokAsset;
  _uid?: string;
}

export interface PartnersBlok {
  partners?: PartnerBlok[];
}

export interface ProgrammationCardBlok {
  title?: string;
  media?: StoryblokAsset;
  link_label?: string;
  link?: StoryblokMultilink;
  content?: (HeadlineBlok | ParagraphBlok)[];
  _uid?: string;
}

export interface ProgrammationCardsSectionBlok {
  content?: (HeadlineBlok | ParagraphBlok)[];
  cards?: ProgrammationCardBlok[];
}

export interface TeaserBlok {
  headline?: string;
}

export interface ContactFormBlok {
  /* Empty – configurable via Storyblok placement only */
}

export type StoryblokComponent = (
  | ArticleContentBlok
  | BlogPageBlok
  | BlogPreviewBlok
  | CenteredTextBlockBlok
  | ChefCardBlok
  | ChefsAndPitmastersBlok
  | GridBlok
  | MasonryGridBlok
  | EventBannerBlok
  | FeatureBlok
  | GlobalConfigBlok
  | GridBlok
  | HeadlineBlok
  | HeroVideoBlok
  | LinkBlok
  | MediaBlok
  | MenuItemBlok
  | PageBlok
  | ParagraphBlok
  | PartnerBlok
  | PartnersBlok
  | ProgrammationCardBlok
  | ProgrammationCardsSectionBlok
  | TeaserBlok
  | ContactFormBlok
) &
  StoryblokComponentBase;
